<?php

namespace Checnes\RegistroBundle\Repository;

/**
 * AnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnoRepository extends \Doctrine\ORM\EntityRepository
{
}
