<?php

namespace Checnes\RegistroBundle\Repository;

/**
 * AsistenciaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsistenciaEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
