<?php

namespace Checnes\RegistroBundle\Repository;

/**
 * ControlAccesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlAccesoRepository extends \Doctrine\ORM\EntityRepository
{
}
