<?php

namespace Checnes\RegistroBundle\Repository;

/**
 * EventoParticipanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoParticipanteRepository extends \Doctrine\ORM\EntityRepository
{
}
