<?php

namespace Checnes\RegistroBundle\Repository;

/**
 * MenuXRolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuXRolRepository extends \Doctrine\ORM\EntityRepository
{
}
