<?php

namespace Checnes\RegistroBundle\Repository;

/**
 * otroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class otroRepository extends \Doctrine\ORM\EntityRepository
{
}
