<?php

namespace Checnes\RegistroBundle\Repository;

/**
 * rolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rolRepository extends \Doctrine\ORM\EntityRepository
{
}
