<?php

namespace Checnes\RegistroBundle\Repository;

/**
 * TipoActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoActividadRepository extends \Doctrine\ORM\EntityRepository
{
}
